name: CI Security Scanning Matrix
on: 
    push:
        branches: [ "main" , "master" , "feature/*" ]
    pull_request:
        branches: [ "main" , "master" , "feature/*" ]
jobs:
    trufflehog-secrets-scan:
        name: Secret Detection (TruffleHog)
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code repository
              uses: actions/checkout@v4

            - name: Run TruffleHog OSS Scanner
              uses: trufflesecurity/trufflehog@main
              with:
                extra_args: --only-verified